#!groovy

stage "before input"
node {
    echo "TRACER : before input"
}

def appInput

stage "input stage"
timeout(time: 1, unit: 'DAYS') {
    appInput = input(id: 'Apps', message: 'Which application(s) ?', parameters: [[$class: 'ChoiceParameter', choiceType: 'PT_MULTI_SELECT', description: '', filterable: false, name: 'app', randomName: 'choice-parameter-444855049411275', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: false, script: ''], script: [classpath: [], sandbox: false, script: 'return [\'abc\',\'def\',\'ijk\',\'xyz\',\'all\']']]]], submitterParameter: 'whoApproved')
}

stage "after input"
node {
    echo "TRACER : after input : " + appInput
}

