#!groovy

stage "before input"
node {
    echo "TRACER : before input"
}

def fooInput

stage "input stage"
timeout(time: 1, unit: 'DAYS') {
    fooInput = input(
                    id: 'userInput', 
                    message: 'Which apps?',
                    parameters: [
                        [$class: 'hudson.model.StringParameterDescription', description: 'Foo desc', name: 'foo', defaultValue: '123']
                    ])
}

stage "after input"
node {
    echo "TRACER : after input : " + fooInput
}

